apiVersion: v1
kind: Secret
metadata:
  name: stateful-flask-secret
  namespace: stateful-namespace
type: Opaque
data:
  DB_USER: c3RhdGVmdWwtZmxhc2stdXNlcg==
  DB_PASSWORD: c3RhdGVmdWwtZmxhc2stcGFzc3dvcmQ=
  DB_HOST: cG9zdGdyZXMucG9zdGdyZXNzLW5hbWVzcGFjZS5zdmMuY2x1c3Rlci5sb2NhbA==
  DB_NAME: c3RhdGVmdWwtZmxhc2stZGI=
  DB_PORT: NTQzMg==

