apiVersion: v1
kind: Service
metadata:
  name: stateful-flask
  namespace: stateful-namespace
spec:
  selector:
    app: stateful-flask
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
