apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateful-flask-deployment
  namespace: stateful-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateful-flask
  template:
    metadata:
      labels:
        app: stateful-flask
    spec:
      containers:
      - image: daredrexel/stateful-flask:v0
        name: stateful-flask
        ports:
        - containerPort: 5000
        imagePullPolicy : Always
        resources:
          requests: 
            memory: "64Mi"
            cpu: "200m"
          limits: 
            memory: "128Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /tasks
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        readinessProbe: 
          httpGet:
            path: /tasks
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 15
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: stateful-flask-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stateful-flask-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: stateful-flask-secret
              key: DB_HOST 
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: stateful-flask-secret
              key: DB_NAME
        - name: DB_PORT
          valueFrom: 
            secretKeyRef:
              name: stateful-flask-secret
              key: DB_PORT

            

            

## ddd